/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualAluno;
import aluno.Persistencia.DadosAlunoGraduacao;
import alunoClass.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import javax.swing.JTable;
/**
 *
 * @author Luiz Hebruque
 */
public class ConsultaAlunoGraduacao extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaAlunoGraduacao
     */
    public ConsultaAlunoGraduacao() {
        initComponents();
        showTable(AGTable);
        
    }
    
    public static  void showTable(JTable a)
    {
        
        String []colunas = new String[]{"Nome", "Endereço", "Telefone", "CPF", "Curso", "Situacao", "Instituição"};
        String [][]dados = new String[0][0];
        
        
        DefaultTableModel dtm = new DefaultTableModel(dados, colunas);
        a.setModel(dtm);
        String situacao = "";
        int i = 0;
        for (AlunoGraduacao p : DadosAlunoGraduacao.getAluno()){  
            
            if(p.getSituacao() == 1)
                 situacao = "Matriculado";
            if(p.getSituacao() == 2)
                 situacao = "Trancou";
            if(p.getSituacao() == 3)
                 situacao = "Desistiu";
            
            
           Object[] x = {p.getNome(), p.getEndereco(), p.getTelefone(), p.getCpf() ,p.getCurso1(),situacao, p.getInstituicao()};
            dtm.insertRow(i, x);
            i++;
        }
    }        
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AGTable = new javax.swing.JTable();
        capicheButton = new javax.swing.JButton();
        eraseROW = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela Graduação");

        AGTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereco", "Telefone", "CPF", "Curso", "Situacao", "Instuição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AGTable);

        capicheButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/accept.png"))); // NOI18N
        capicheButton.setText("Finalizar Conuslta");
        capicheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capicheButtonActionPerformed(evt);
            }
        });

        eraseROW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/delete.png"))); // NOI18N
        eraseROW.setText("Apagar");
        eraseROW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseROWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eraseROW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(capicheButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capicheButton)
                    .addComponent(eraseROW))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void capicheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capicheButtonActionPerformed
        dispose();
    }//GEN-LAST:event_capicheButtonActionPerformed

    private void eraseROWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseROWActionPerformed
        if(AGTable.getSelectedRow()>=0){
            DadosAlunoGraduacao.excluirAG(AGTable.getSelectedRow());
            showTable(AGTable);
        }else
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        
    }//GEN-LAST:event_eraseROWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAlunoGraduacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AGTable;
    private javax.swing.JButton capicheButton;
    private javax.swing.JButton eraseROW;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
