/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualAluno;

import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Hebruque
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        cadAluno = new javax.swing.JButton();
        cadCurso = new javax.swing.JButton();
        cadDis = new javax.swing.JButton();
        cadFun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cadDis1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Consultas = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        consCD = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        consTec = new javax.swing.JMenuItem();
        dis = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        de = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("jMenu2");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão Acadêmica");

        cadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/add.png"))); // NOI18N
        cadAluno.setText("Cadastrar Aluno");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });

        cadCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/add.png"))); // NOI18N
        cadCurso.setText("Cadastrar Curso");
        cadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCursoActionPerformed(evt);
            }
        });

        cadDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/add.png"))); // NOI18N
        cadDis.setText("Cadastrar Disciplina");
        cadDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDisActionPerformed(evt);
            }
        });

        cadFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/add.png"))); // NOI18N
        cadFun.setText("Cadastrar Funcionário");
        cadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFunActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/transparente azul03.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        cadDis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/add.png"))); // NOI18N
        cadDis1.setText("   Cadastrar Projeto Pesquisa");
        cadDis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDis1ActionPerformed(evt);
            }
        });

        Consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/database_go.png"))); // NOI18N
        Consultas.setText("Consultas");
        Consultas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ConsultasMouseMoved(evt);
            }
        });
        Consultas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConsultasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConsultasFocusLost(evt);
            }
        });
        Consultas.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
                ConsultasMenuDragMouseDragged(evt);
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/book.png"))); // NOI18N
        jMenu3.setText("Cursos");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/book.png"))); // NOI18N
        jMenuItem5.setText("Graduação");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/book.png"))); // NOI18N
        jMenuItem6.setText("Pós Graduação");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        Consultas.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/group.png"))); // NOI18N
        jMenu1.setText("Discentes");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/group.png"))); // NOI18N
        jMenuItem2.setText("Graduandos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/group.png"))); // NOI18N
        jMenuItem4.setText("Pos Graduandos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        Consultas.add(jMenu1);

        consCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/group.png"))); // NOI18N
        consCD.setText("Corpo Docente");
        consCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consCDActionPerformed(evt);
            }
        });
        Consultas.add(consCD);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/zoom.png"))); // NOI18N
        jMenuItem10.setText("Iniciação Científica");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Consultas.add(jMenuItem10);

        consTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/wrench.png"))); // NOI18N
        consTec.setText("Técnicos ");
        consTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consTecActionPerformed(evt);
            }
        });
        Consultas.add(consTec);

        dis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/unnamed.png"))); // NOI18N
        dis.setText("Disciplina");
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        Consultas.add(dis);

        jMenuBar1.add(Consultas);

        Ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitario/Imagens/information.png"))); // NOI18N
        Ajuda.setText("Informações");

        de.setText("Quem desenvolveu?");
        de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deActionPerformed(evt);
            }
        });
        Ajuda.add(de);

        jMenuBar1.add(Ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadFun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadDis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadDis1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(cadDis)
                        .addGap(18, 18, 18)
                        .addComponent(cadAluno)
                        .addGap(18, 18, 18)
                        .addComponent(cadCurso)
                        .addGap(18, 18, 18)
                        .addComponent(cadFun)
                        .addGap(18, 18, 18)
                        .addComponent(cadDis1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consCDActionPerformed
        ConsultaProfessor a = new ConsultaProfessor();
        a.setVisible(true);
    }//GEN-LAST:event_consCDActionPerformed

    private void ConsultasMenuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_ConsultasMenuDragMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultasMenuDragMouseDragged

    private void ConsultasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConsultasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultasFocusGained

    private void ConsultasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConsultasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultasFocusLost

    private void ConsultasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultasMouseMoved
    // Faz a chamada para abertura da tela para o cadastro de um curso;
    // O usuário pode escolher entre um curso Graduacao ou Pos Graduacao.
    private void cadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCursoActionPerformed
        CadastrarCurso c = new CadastrarCurso();
        c.setVisible(true);
    }//GEN-LAST:event_cadCursoActionPerformed

    private void cadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFunActionPerformed
        CadastrarFuncionario f = new CadastrarFuncionario();
        f.setVisible(true);
    }//GEN-LAST:event_cadFunActionPerformed

    private void consTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consTecActionPerformed
          ConsultaTecnico a = new ConsultaTecnico();
          a.setVisible(true);
    }//GEN-LAST:event_consTecActionPerformed

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
      CadastrarAluno a = new CadastrarAluno();
      a.setVisible(true);
    }//GEN-LAST:event_cadAlunoActionPerformed

    // Realiza o cadastro de uma disciplina
    private void cadDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDisActionPerformed
       CadastrarDisciplina cds = new CadastrarDisciplina(); 
       cds.setVisible(true);
    }//GEN-LAST:event_cadDisActionPerformed

    private void cadDis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDis1ActionPerformed
        GraduacaoCadastrarIC gci = new GraduacaoCadastrarIC();
        gci.setVisible(true);
    }//GEN-LAST:event_cadDis1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ConsultaAlunoGraduacao a = new ConsultaAlunoGraduacao();
        a.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
          ConsultaAlunoPos a = new ConsultaAlunoPos();
          a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
          ConsultarDisciplina a = new ConsultarDisciplina();
          a.setVisible(true);
    }//GEN-LAST:event_disActionPerformed

    private void deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deActionPerformed
        JOptionPane.showMessageDialog(null, "Luiz Henrique Dias Lima - 11721BSI261 \n" + "Guilherme Henrique de Araújo Santos - 11721BSI220");
        
    }//GEN-LAST:event_deActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ConsultarCursoGrad ccg = new ConsultarCursoGrad();
        ccg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       ConsultarCursoPos ccp = new ConsultarCursoPos();
       ccp.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       ConsultarPesquisasGraduacao cpg = new ConsultarPesquisasGraduacao();
       cpg.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenu Consultas;
    private javax.swing.JButton cadAluno;
    private javax.swing.JButton cadCurso;
    private javax.swing.JButton cadDis;
    private javax.swing.JButton cadDis1;
    private javax.swing.JButton cadFun;
    private javax.swing.JMenuItem consCD;
    private javax.swing.JMenuItem consTec;
    private javax.swing.JMenuItem de;
    private javax.swing.JMenuItem dis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
